### ISSUE TITLE
Ionic Serve Running Error

### ISSUE THREAD

**Issue by littlefieldnick** [OpenHDS/ionic-client#36]
When running using ionic serve:

 Error: Uncaught (in promise): [object Object]
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:19174
    at rejected (http://localhost:8100/build/main.js:790:89)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:4982:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)

**Comment by bruceMacLeod** [comment]
The fix works on my machine!
